###
FROM registry.access.redhat.com/ubi8/openjdk-17:1.14

ENV LANGUAGE='en_US:en'
COPY --chown=185 target/*.jar /deployments/
EXPOSE 8080
USER 185

# JAVA_OPTIONS could be baked in, but not a flexible option
#ENV JAVA_OPTIONS="-Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.rmi.port=9010"

ENV JAVA_APP_JAR="/deployments/bala.app-1.0.0.jar"
